const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Behaviors.Fade,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Mouse.Cnds.OnObjectClicked
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{TiledBackground2: 0},
	{Solid: 0},
	{Tilemap: 0},
	{Platform: 0},
	{Sprite: 0},
	{START: 0},
	{mulai: 0},
	{TextFreya: 0},
	{NICK: 0},
	{Mouse: 0},
	{Audio: 0},
	{Keyboard: 0},
	{score: 0},
	{Fade: 0},
	{Coin: 0},
	{Sprite2: 0},
	{arah: 0},
	{healt: 0},
	{Sprite3: 0},
	{hp: 0},
	{Text: 0},
	{Sprite4: 0},
	{Text2: 0},
	{Sprite5: 0},
	{Score: 0},
	{HP: 0},
	{Score2: 0},
	{HP2: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Sprite: class extends self.ISpriteInstance {},
	START: class extends self.ITextInstance {},
	mulai: class extends self.ISpriteInstance {},
	TextFreya: class extends self.ITextInstance {},
	NICK: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	score: class extends self.ITextInstance {},
	Coin: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	hp: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite5: class extends self.ISpriteInstance {}
}