const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Behaviors.scrollto,
		C3.Behaviors.Bullet,
		C3.Behaviors.Fade,
		C3.Plugins.progressbar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.progressbar.Acts.SetProgress,
		C3.Behaviors.Fade.Acts.SetFadeInTime,
		C3.Behaviors.Fade.Acts.SetFadeOutTime,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.SetVar
	];
};
self.C3_JsPropNameTable = [
	{BG1_1: 0},
	{BG1_2: 0},
	{BG1_3: 0},
	{BG1_4: 0},
	{Solid: 0},
	{Tilemap: 0},
	{Direction: 0},
	{Platform: 0},
	{BoundTo: 0},
	{Wizard: 0},
	{Audio: 0},
	{Title: 0},
	{Start_Button: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{ScrollTo: 0},
	{Camera: 0},
	{Bullet: 0},
	{Fade: 0},
	{BAttack: 0},
	{Tilemap2: 0},
	{Health: 0},
	{Slime: 0},
	{Rotate: 0},
	{Portal: 0},
	{BG2_1: 0},
	{BG2_2: 0},
	{BG2_3: 0},
	{BG2_4: 0},
	{BG3_1: 0},
	{BG3_2: 0},
	{BG3_3: 0},
	{BG3_4: 0},
	{Black: 0},
	{TheEnd: 0},
	{Credit: 0},
	{Restart_Button: 0},
	{ProgressBar: 0},
	{Score: 0},
	{Tree: 0},
	{Bush: 0},
	{Bush2: 0},
	{Stone: 0},
	{Stone2: 0}
];

self.InstanceType = {
	BG1_1: class extends self.ITiledBackgroundInstance {},
	BG1_2: class extends self.ITiledBackgroundInstance {},
	BG1_3: class extends self.ITiledBackgroundInstance {},
	BG1_4: class extends self.ITiledBackgroundInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Wizard: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Title: class extends self.ITextInstance {},
	Start_Button: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Camera: class extends self.ISpriteInstance {},
	BAttack: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	Slime: class extends self.ISpriteInstance {},
	Rotate: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	BG2_1: class extends self.ITiledBackgroundInstance {},
	BG2_2: class extends self.ITiledBackgroundInstance {},
	BG2_3: class extends self.ITiledBackgroundInstance {},
	BG2_4: class extends self.ITiledBackgroundInstance {},
	BG3_1: class extends self.ITiledBackgroundInstance {},
	BG3_2: class extends self.ITiledBackgroundInstance {},
	BG3_3: class extends self.ITiledBackgroundInstance {},
	BG3_4: class extends self.ITiledBackgroundInstance {},
	Black: class extends self.ISpriteInstance {},
	TheEnd: class extends self.ITextInstance {},
	Credit: class extends self.ITextInstance {},
	Restart_Button: class extends self.ISpriteInstance {},
	ProgressBar: class extends self.IProgressBarInstance {},
	Score: class extends self.ITextInstance {},
	Tree: class extends self.ISpriteInstance {},
	Bush: class extends self.ISpriteInstance {},
	Bush2: class extends self.ISpriteInstance {},
	Stone: class extends self.ISpriteInstance {},
	Stone2: class extends self.ISpriteInstance {}
}