const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.Physics,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Plugins.Touch,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Spritefont2.Cnds.PickByUID,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Physics.Acts.ApplyImpulse,
		C3.Behaviors.Physics.Acts.SetWorldGravity,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Acts.Wait
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{Physics: 0},
	{Rotate: 0},
	{FlappyBrid: 0},
	{BGT1: 0},
	{Touch: 0},
	{Keyboard: 0},
	{pipia_atas: 0},
	{pipia_bawah: 0},
	{tanahBagianBawah: 0},
	{cobi_Score: 0},
	{Text: 0},
	{SpriteFont: 0},
	{uI_Hitam: 0},
	{gameover: 0},
	{Text2: 0},
	{Sprite: 0},
	{GameAktif: 0},
	{Data_Score: 0},
	{Data_Kecepatan: 0},
	{Data_WaktuSpawe: 0},
	{DataRamdom: 0}
];

self.InstanceType = {
	FlappyBrid: class extends self.ISpriteInstance {},
	BGT1: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	pipia_atas: class extends self.ISpriteInstance {},
	pipia_bawah: class extends self.ISpriteInstance {},
	tanahBagianBawah: class extends self.ISpriteInstance {},
	cobi_Score: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	uI_Hitam: class extends self.ISpriteInstance {},
	gameover: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {}
}